{% set name = "uvloop" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ddf6baf9cf11a1a22c71487f39f15b2cf78eb5bde7e5b45fbb99e8a9d91b9e1
  patches:
    - 0001-Prefer-SO_REUSEPORT-over-uv.SO_REUSEPORT.patch

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --global-option='build_ext' --global-option='--cython-always' --global-option='--use-system-libuv'
  skip: true  # [py<37 or win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - make  # [unix]
  host:
    - python
    - cython <3
    - pip
    - libuv
  run:
    - python
    - {{ pin_compatible("libuv", max_pin="x") }}

test:
  imports:
    - uvloop

about:
  home: http://github.com/MagicStack/uvloop
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
  summary: Ultra fast implementation of asyncio event loop on top of libuv.
  description: |
    uvloop is a fast, drop-in replacement of the built-in asyncio event loop.
    uvloop is implemented in Cython and uses libuv under the hood.
  doc_url: http://uvloop.readthedocs.org
  dev_url: https://github.com/MagicStack/uvloop

extra:
  recipe-maintainers:
    - nehaljwani
    - carlodri
    - jakirkham
